/**
 * Gateway-generated metadata attached to every request. Used for
 * observability, correlation, and soft-deadline awareness inside the handler.
 * @remarks
 * Produced exclusively by `zerly-gateway-server` — handlers must treat every
 * field as authoritative and MUST NOT attempt to synthesize values of this
 * shape themselves. The fields are deliberately flat to keep the wire
 * envelope small and JSON-friendly.
 */
export interface IGatewayRequestMeta {
  /**
   * Unique per-request identifier (ULID) generated by `zerly-gateway-server`.
   * @remarks
   * Echoed in the HTTP response header `X-Request-Id` so clients can correlate
   * logs. Handlers should include this in their own structured log entries.
   */
  readonly requestId: string;

  /**
   * W3C Trace Context `traceparent` header, if present in the incoming request.
   * @remarks
   * Absent when the upstream client did not propagate a trace. Handlers that
   * open child spans should create a new root span when this field is missing
   * rather than fabricating a parent id.
   */
  readonly traceparent?: string;

  /**
   * Remote client IP after `X-Forwarded-For` resolution.
   * @remarks
   * The gateway's trusted-proxy list determines how many `X-Forwarded-For`
   * hops are honored; handlers should treat this value as already sanitized
   * and avoid re-parsing the header themselves.
   */
  readonly remoteAddr: string;

  /** Unix milliseconds when the gateway accepted the request. */
  readonly receivedAt: number;

  /**
   * Remaining time (in milliseconds) until the gateway's HTTP timeout fires.
   * @remarks
   * Handlers MAY use this as a soft deadline for internal operations — for
   * example, passing it as a DB query timeout to avoid work the gateway will
   * discard anyway.
   */
  readonly timeoutMs: number;
}
