export const MICROSERVICE_SERVER_PROVIDER = Symbol('MICROSERVICE_SERVER_PROVIDER');

export const MICROSERVICE_CLIENT_PROVIDER = Symbol('MICROSERVICE_CLIENT_PROVIDER');

export const MICROSERVICE_OPTIONS = Symbol('MICROSERVICE_OPTIONS');
